# Generated by Django 6.0 on 2026-01-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Title')),
                ('text', models.TextField(verbose_name="Note's text")),
                ('reminder', models.DateTimeField(verbose_name='remind me on')),
            ],
        ),
    ]
