# Generated by Django 6.0 on 2026-01-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Anonimus', max_length=50, verbose_name='Name'),
        ),
    ]
